name: 每日60s读懂世界推送
on:
  # 定时任务 GitHub使用UTC时区！北京时间 = UTC+8
  # UTC 2:00  = 北京时间 10:00（推荐，等接口更新完成）
  schedule:
    - cron: "0 1 * * *"
  # 支持手动点击按钮测试运行
  workflow_dispatch:

jobs:
  push_news:
    runs-on: ubuntu-latest
    steps:
      - name: 请求图片并推送到微信
        env:
          WPUSH_KEY: ${{ secrets.WPUSH_KEY }}
        run: |
          curl "https://wpush.cn/api/push/$WPUSH_KEY" \
          -F "title=每日60s读懂世界" \
          -F "image=https://60s.viki.moe/v2/60s?encoding=image-proxy"
