name: 每日60s读懂世界推送
on:
  schedule:
    # UTC 2点 = 北京时间10点（推荐，接口此时已经更新当日图片）
    - cron: "0 1 * * *"
  workflow_dispatch: #支持手动测试运行

jobs:
  push_news:
    runs-on: ubuntu-latest
    env:
      WPUSH_APIKEY: ${{ secrets.WPUSH_APIKEY }}
    steps:
      - name: 调用新版WPush接口推送新闻图片
        run: |
          curl --location 'https://api.wpush.cn/api/v1/send' \
          --header 'Content-Type: application/json' \
          --data '{
            "apikey": "${WPUSH_APIKEY}",
            "title": "每日60s读懂世界",
            "content": ""
          }'
